// src/App.tsx
import React, { useState, ChangeEvent } from "react";
import {
  FolderTree,
  Download,
  AlertCircle,
  CheckCircle,
  Sun,
  Moon,
} from "lucide-react";
import useTheme from "./useTheme";
import { parseGitignore, isPathIgnored } from "./utils";

interface TreeNode {
  name: string;
  type: "folder" | "file";
  children?: TreeNode[];
}

function App() {
  const [folderStructure, setFolderStructure] = useState<string>("");
  const [treeData, setTreeData] = useState<TreeNode[]>([]);
  const [isLoading, setIsLoading] = useState<boolean>(false);
  const [error, setError] = useState<string>("");
  const { isDarkMode, toggleTheme } = useTheme();

  const handleFolderSelect = async (event: ChangeEvent<HTMLInputElement>) => {
    const files = event.target.files;
    if (files && files.length > 0) {
      setIsLoading(true);
      setError("");
      try {
        const { tree, structure, treeNodes } = await listFolderContents(files);
        setFolderStructure(structure);
        setTreeData(treeNodes);
        downloadTextFile(structure, "folder_structure.txt");
      } catch (err) {
        setError("Ocurrió un error al procesar los archivos.");
      } finally {
        setIsLoading(false);
      }
    }
  };

  const listFolderContents = async (
    fileList: FileList
  ): Promise<{ tree: string; structure: string; treeNodes: TreeNode[] }> => {
    let treeStructure = "Folder Structure:\n\n";
    let fileContents = "\n\nFile Contents:\n";
    const files = Array.from(fileList);

    // Buscar el archivo .gitignore
    const gitignoreFile = files.find((file) => file.name === ".gitignore");
    let ignorePatterns: string[] = [];

    if (gitignoreFile) {
      try {
        const gitignoreContent = await readFileContent(gitignoreFile);
        ignorePatterns = parseGitignore(gitignoreContent);
      } catch (error) {
        console.error("Error al leer .gitignore:", error);
      }
    }

    // Filtrar los archivos según .gitignore
    const filteredFiles = files.filter((file) => {
      const relativePath = file.webkitRelativePath || file.name;
      // Omitir el propio .gitignore si lo deseas
      if (relativePath === ".gitignore") return false;
      return !isPathIgnored(relativePath, ignorePatterns);
    });

    if (filteredFiles.length === 0) {
      return { tree: treeStructure, structure: fileContents, treeNodes: [] };
    }

    const rootPath = filteredFiles[0].webkitRelativePath.split("/")[0];

    const root: TreeNode = {
      name: rootPath,
      type: "folder",
      children: [],
    };

    const addToTree = async (path: string[], file: File) => {
      let currentNode = root;

      for (let i = 0; i < path.length; i++) {
        const part = path[i];
        let child = currentNode.children?.find(
          (c) => c.name === part && c.type === "folder"
        );

        if (!child) {
          child = {
            name: part,
            type: "folder",
            children: [],
          };
          currentNode.children?.push(child);
        }

        currentNode = child;
      }

      const fileName = file.name;
      const fileNode: TreeNode = {
        name: fileName,
        type: "file",
      };

      currentNode.children?.push(fileNode);
    };

    root.children = [];

    for (const file of filteredFiles) {
      const relativePath = file.webkitRelativePath || file.name;
      const parts = relativePath.split("/").filter(Boolean);
      if (parts.length > 1) {
        const folderPath = parts.slice(1, -1);
        await addToTree(folderPath, file);
      } else {
        await addToTree([], file);
      }
    }

    const generateTreeText = (node: TreeNode, prefix: string = ""): string => {
      let treeStr = "";

      const displayName = node.type === "folder" ? `${node.name}/` : node.name;
      treeStr += `${prefix}${displayName}\n`;

      if (node.children && node.children.length > 0) {
        node.children.forEach((child, index) => {
          const isLast = index === node.children!.length - 1;
          const connector = isLast ? "└─ " : "├─ ";
          const newPrefix = prefix + (isLast ? "    " : "│   ");
          const childDisplayName =
            child.type === "folder" ? `${child.name}/` : child.name;
          treeStr += `${prefix}${connector}${childDisplayName}\n`;
          if (child.type === "folder" && child.children) {
            treeStr += generateTreeText(child, newPrefix);
          }
        });
      }

      return treeStr;
    };

    treeStructure += generateTreeText(root);

    // Generar treeNodes para la visualización (opcional)
    const generateTreeNodes = (node: TreeNode): TreeNode[] => {
      if (!node.children) return [];

      return node.children.map((child) => ({
        ...child,
        children:
          child.type === "folder" ? generateTreeNodes(child) : undefined,
      }));
    };

    const treeNodes = generateTreeNodes(root);

    for (const file of filteredFiles) {
      const relativePath = file.webkitRelativePath || file.name;
      const fileExtension = relativePath.split(".").pop()?.toLowerCase();

      const isTextFile = [
        "txt",
        "js",
        "jsx",
        "ts",
        "tsx",
        "css",
        "html",
        "json",
        "md",
        "py",
      ].includes(fileExtension || "");

      fileContents += `\nFile: ${relativePath}\n`;
      fileContents += `${"=".repeat(relativePath.length + 6)}\n`;

      if (isTextFile) {
        try {
          const content = await readFileContent(file);
          fileContents += `${content}\n\n`;
        } catch (readError) {
          fileContents += "Error al leer el contenido del archivo.\n\n";
        }
      } else {
        fileContents += "Contenido binario o no legible.\n\n";
      }
    }

    const fullStructure = treeStructure + fileContents;

    return { tree: treeStructure, structure: fullStructure, treeNodes };
  };

  const readFileContent = (file: File): Promise<string> => {
    return new Promise((resolve, reject) => {
      const reader = new FileReader();
      reader.onload = (event) => {
        if (event.target) {
          const content = event.target.result as string;
          resolve(content);
        }
      };
      reader.onerror = (error) => reject(error);
      reader.readAsText(file);
    });
  };

  const downloadTextFile = (content: string, fileName: string) => {
    const element = document.createElement("a");
    const file = new Blob([content], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = fileName;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  };

  return (
    <div
      className={`min-h-screen flex flex-col items-center justify-center p-4 transition-colors duration-500 ${
        isDarkMode ? "bg-gray-900" : "bg-gray-100"
      }`}
    >
      <div className="w-full max-w-2xl">
        <div className="flex flex-col items-center justify-between mb-6">
          <h1
            className={`text-4xl font-extrabold text-center transition-colors duration-500 ${
              isDarkMode ? "text-white" : "text-gray-800"
            }`}
          >
            📁 Explorador de Carpetas
          </h1>
          <p
            className={`mt-2 text-center text-lg transition-colors duration-500 ${
              isDarkMode ? "text-gray-300" : "text-gray-700"
            }`}
          >
            Analiza y visualiza la estructura de tus carpetas de manera
            sencilla.
          </p>
          <button
            onClick={toggleTheme}
            className="mt-4 p-2 rounded-full bg-gray-200 dark:bg-gray-700 hover:bg-gray-300 dark:hover:bg-gray-600 transition-colors duration-300"
            aria-label="Toggle Dark Mode"
          >
            {isDarkMode ? (
              <Sun className="w-5 h-5 text-yellow-400" />
            ) : (
              <Moon className="w-5 h-5 text-gray-800" />
            )}
          </button>
        </div>

        <div
          className={`p-8 rounded-lg shadow-md transition-colors duration-500 ${
            isDarkMode ? "bg-gray-800" : "bg-white"
          }`}
        >
          <label
            htmlFor="folder-input"
            className="flex items-center justify-center w-full px-4 py-2 bg-blue-500 text-white rounded-lg cursor-pointer hover:bg-blue-600 transition-colors duration-300"
          >
            <FolderTree className="mr-2" />
            Seleccionar Carpeta
          </label>
          <input
            id="folder-input"
            type="file"
            webkitdirectory="true"
            directory=""
            className="hidden"
            onChange={handleFolderSelect}
          />

          {isLoading && (
            <div className="flex items-center mt-6">
              <svg
                className="animate-spin -ml-1 mr-3 h-5 w-5 text-blue-500"
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
              >
                <circle
                  className="opacity-25"
                  cx="12"
                  cy="12"
                  r="10"
                  stroke="currentColor"
                  strokeWidth="4"
                ></circle>
                <path
                  className="opacity-75"
                  fill="currentColor"
                  d="M4 12a8 8 0 018-8v8H4z"
                ></path>
              </svg>
              <span
                className={`transition-colors duration-500 ${
                  isDarkMode ? "text-gray-300" : "text-gray-700"
                }`}
              >
                Procesando...
              </span>
            </div>
          )}

          {error && (
            <div className="flex items-center mt-6 text-red-600">
              <AlertCircle className="mr-2 w-5 h-5" />
              <span>{error}</span>
            </div>
          )}

          {folderStructure && !isLoading && !error && (
            <div className="mt-6">
              <div className="flex items-center justify-between mb-4">
                <h2
                  className={`text-2xl font-semibold transition-colors duration-500 ${
                    isDarkMode ? "text-white" : "text-gray-800"
                  }`}
                >
                  Estructura de la Carpeta
                </h2>
                <button
                  onClick={() =>
                    downloadTextFile(folderStructure, "folder_structure.txt")
                  }
                  className="flex items-center px-4 py-2 bg-green-500 text-white rounded-lg hover:bg-green-600 transition-colors duration-300"
                >
                  <Download className="mr-2 w-5 h-5" />
                  Descargar
                </button>
              </div>
              <div
                className={`p-4 rounded-md shadow-inner overflow-x-auto mb-6 transition-colors duration-500 ${
                  isDarkMode ? "bg-gray-700" : "bg-gray-50"
                }`}
              >
                <pre
                  className={`whitespace-pre-wrap font-mono text-sm transition-colors duration-500 ${
                    isDarkMode ? "text-gray-200" : "text-gray-800"
                  }`}
                >
                  {folderStructure}
                </pre>
              </div>

              <div className="flex items-center mt-4 text-green-600">
                <CheckCircle className="mr-2 w-5 h-5" />
                <span>¡Estructura generada y descargada exitosamente!</span>
              </div>
            </div>
          )}
        </div>

        <div
          className={`mt-8 p-4 rounded-lg shadow-md flex items-center justify-center transition-colors duration-500 ${
            isDarkMode ? "bg-black" : "bg-white"
          }`}
        >
          <span
            className={`text-sm font-medium ${
              isDarkMode ? "text-white" : "text-gray-800"
            }`}
          >
            Creado por{" "}
            <a
              href="https://github.com/JohanMorales211"
              target="_blank"
              rel="noopener noreferrer"
              className="underline"
            >
              Johan Morales
            </a>
          </span>
        </div>
      </div>
    </div>
  );
}

export default App;

// src/app/app.component.ts
import { Component } from '@angular/core';
import { trigger, transition, style, animate } from '@angular/animations';
import { FolderProcessorService, TreeNode } from './services/folder-processor.service';
import { DomSanitizer, SafeHtml } from '@angular/platform-browser';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
  animations: [
    trigger('fadeSlideIn', [
      transition(':enter', [
        style({ opacity: 0, transform: 'translateY(20px)' }),
        animate('500ms ease-out', style({ opacity: 1, transform: 'translateY(0)' })),
      ]),
    ]),
    trigger('resultsContainer', [
       transition(':enter', [
        style({ opacity: 0, transform: 'scale(0.95)' }),
        animate('400ms 100ms ease-out', style({ opacity: 1, transform: 'scale(1)' })),
      ]),
    ])
  ]
})
export class AppComponent {
  treeData: TreeNode | null = null;
  folderStructureText = '';
  isLoading = false;
  progress: number | null = null;
  error: string | null = null;
  selectedFolderName: SafeHtml | string = '';

  title = 'folder-explorer'; 

  constructor(
    private folderProcessor: FolderProcessorService,
    private sanitizer: DomSanitizer
  ) {}

  onFolderSelected(event: Event): void {
    const inputElement = event.target as HTMLInputElement;
    const files = inputElement.files;
    if (!files || files.length === 0) { return; }
    this.isLoading = true;
    this.error = null;
    this.treeData = null;
    this.progress = 0;
    const rootPath = (files[0] as any).webkitRelativePath;
    const folderName = rootPath ? rootPath.split('/')[0] : 'archivos';
    this.selectedFolderName = this.sanitizer.bypassSecurityTrustHtml(`Carpeta seleccionada: <strong>${folderName}</strong>`);
    this.folderProcessor.processFolder(files).subscribe({
      next: (e) => {
        if (e.type === 'progress') this.progress = e.value;
        else if (e.type === 'complete') {
          this.treeData = e.tree;
          this.folderStructureText = e.structureText;
          this.downloadTextFile(e.structureText, `estructura_${e.tree.name}.txt`);
        } else if (e.type === 'error') this.error = e.message;
      },
      error: () => { this.error = 'Ocurrió un error inesperado.'; this.isLoading = false; },
      complete: () => { this.isLoading = false; this.progress = null; }
    });
  }

  downloadTextFile(content: string, fileName: string): void {
    const element = document.createElement("a");
    const file = new Blob([content], { type: "text/plain" });
    element.href = URL.createObjectURL(file);
    element.download = fileName;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
  }

  resetState(): void {
    this.selectedFolderName = '';
    this.treeData = null;
    this.error = null;
    this.isLoading = false;
    this.progress = null;
  }
}
<div class="flex flex-col min-h-screen bg-[#111119] text-gray-300" style="font-family: Manrope, 'Noto Sans', sans-serif;">
  
  <header class="w-full max-w-7xl mx-auto px-6 py-4">
    <nav class="flex items-center justify-between">
      
      <div class="flex items-center gap-3 text-white">
        <svg class="w-6 h-6" viewBox="0 0 128 128" xmlns="http://www.w3.org/2000/svg" fill="currentColor">
          <g>
            <path d="M20 44c0-4.4 3.6-8 8-8h28l8 8h44c4.4 0 8 3.6 8 8v48c0 4.4-3.6 8-8 8H28c-4.4 0-8-3.6-8-8V44z" />
            <path d="M20 44h36l8 8H20v-8z" fill="#111119" opacity="0.8"/>
          </g>
        </svg>

        <h1 class="font-bold text-base tracking-tight">Explorador de Carpetas</h1>
      </div>

      <div class="flex items-center gap-5">
        <a href="https://github.com/JohanMorales211" target="_blank" rel="noopener noreferrer" aria-label="Perfil de GitHub" class="text-gray-400 hover:text-white transition-colors duration-300">
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path fill-rule="evenodd" d="M12 2C6.477 2 2 6.477 2 12c0 4.418 2.865 8.168 6.839 9.492.5.092.682-.217.682-.482 0-.237-.009-.868-.014-1.703-2.782.605-3.369-1.343-3.369-1.343-.454-1.158-1.11-1.466-1.11-1.466-.908-.62.069-.608.069-.608 1.003.07 1.531 1.032 1.531 1.032.892 1.53 2.341 1.088 2.91.832.092-.647.35-1.088.636-1.338-2.22-.253-4.555-1.113-4.555-4.951 0-1.093.39-1.988 1.031-2.688-.103-.253-.446-1.272.098-2.65 0 0 .84-.27 2.75 1.026A9.564 9.564 0 0112 6.844c.85.004 1.705.115 2.504.337 1.909-1.296 2.747-1.027 2.747-1.027.546 1.378.203 2.398.1 2.651.64.7 1.03 1.595 1.03 2.688 0 3.848-2.338 4.695-4.566 4.943.359.309.678.92.678 1.855 0 1.338-.012 2.419-.012 2.747 0 .268.18.58.688.482A10.001 10.001 0 0022 12c0-5.523-4.477-10-10-10z" clip-rule="evenodd" /></svg>
        </a>
        <a href="https://www.linkedin.com/in/johan-morales-b3809b206/" target="_blank" rel="noopener noreferrer" aria-label="Perfil de LinkedIn" class="text-gray-400 hover:text-white transition-colors duration-300">
          <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 24 24" aria-hidden="true"><path d="M19 0h-14c-2.761 0-5 2.239-5 5v14c0 2.761 2.239 5 5 5h14c2.762 0 5-2.239 5-5v-14c0-2.761-2.238-5-5-5zm-11 19h-3v-11h3v11zm-1.5-12.268c-.966 0-1.75-.79-1.75-1.764s.784-1.764 1.75-1.764 1.75.79 1.75 1.764-.783 1.764-1.75 1.764zm13.5 12.268h-3v-5.604c0-3.368-4-3.113-4 0v5.604h-3v-11h3v1.765c1.396-2.586 7-2.777 7 2.476v6.759z"/></svg>
        </a>
        <a href="https://johanmorales211.github.io/portafolio-personal/" target="_blank" rel="noopener noreferrer" aria-label="Portafolio Personal" class="text-gray-400 hover:text-white transition-colors duration-300">
           <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M16 7a4 4 0 11-8 0 4 4 0 018 0zM12 14a7 7 0 00-7 7h14a7 7 0 00-7-7z"></path></svg>
        </a>
      </div>
    </nav>
  </header>

  <main class="flex-grow flex flex-col items-center justify-center text-center p-6">
    <div class="w-full max-w-2xl">
      
      <h2 @fadeSlideIn class="text-4xl font-bold text-white tracking-tight">Generador de Estructura de Carpetas</h2>
      <p @fadeSlideIn class="mt-3 text-base text-gray-400">
        Arrastra o selecciona una carpeta para generar un archivo de texto con su estructura y contenido.
      </p>

      <div @fadeSlideIn class="mt-10">
        <label for="folder-input" class="relative block w-full rounded-lg border-2 border-dashed border-gray-700 p-12 text-center hover:border-gray-600 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2 cursor-pointer transition-colors uploader-zone-hover">
          <input id="folder-input" type="file" (change)="onFolderSelected($event)" webkitdirectory class="hidden" [disabled]="isLoading" />

          <ng-container *ngIf="!isLoading && !treeData && !error">
            <p class="mt-2 block text-lg font-semibold text-white">Arrastra y suelta una carpeta aquí</p>
            <p class="mt-1 block text-sm text-gray-400">O haz clic para seleccionar una carpeta</p>
            <div class="mt-6">
              <div class="flex min-w-[84px] max-w-xs mx-auto cursor-pointer items-center justify-center rounded-full h-10 px-4 bg-gray-800 text-white text-sm font-bold leading-normal hover:bg-gray-700 transition-colors">
                <span class="truncate">Seleccionar Carpeta</span>
              </div>
            </div>
          </ng-container>

          <ng-container *ngIf="isLoading">
            <p class="text-lg font-semibold text-white" [innerHTML]="selectedFolderName"></p>
            <p class="mt-2 text-base text-gray-400">Procesando carpeta...</p>
            <div class="mt-4 max-w-xs mx-auto">
              <div class="relative w-full bg-gray-700 rounded-full h-2">
                <div class="bg-violet-400 h-2 rounded-full transition-all duration-300" [style.width.%]="progress"></div>
              </div>
            </div>
          </ng-container>

          <ng-container *ngIf="!isLoading && treeData">
             <p class="text-green-400 text-lg font-bold">¡Estructura generada y descargada!</p>
             <p (click)="$event.preventDefault(); resetState()" class="mt-2 text-sm text-gray-400 hover:text-white underline cursor-pointer">
               Seleccionar otra carpeta
             </p>
          </ng-container>
        </label>
      </div>

      <p *ngIf="error" class="mt-4 text-red-400">{{ error }}</p>

      <div @resultsContainer *ngIf="treeData && !isLoading && !error" class="mt-12 text-left">
         <div class="flex justify-between items-center mb-4">
          <h3 class="text-xl font-bold text-white">Estructura Generada</h3>
           <button 
            (click)="downloadTextFile(folderStructureText, 'estructura_' + (treeData.name) + '.txt')"
            class="inline-flex items-center px-4 py-2 border border-transparent rounded-full font-semibold text-xs text-white bg-green-600 hover:bg-green-700">
            Descargar de Nuevo
          </button>
        </div>
        <div class="bg-[#1a1a24] border border-gray-700 p-4 rounded-lg overflow-x-auto max-h-[500px]">
          <app-folder-tree-view [node]="treeData"></app-folder-tree-view>
        </div>
      </div>

    </div>
  </main>

  <footer @fadeSlideIn class="w-full text-center p-6">
    <p class="text-sm text-gray-500">Hecho por Johan Morales</p>
  </footer>
</div>
